keywords:
  omics:
    - single-cell
    - scRNA-seq
    - transcriptomics
    - multi-omics
    - spatial transcriptomics
    - ATAC-seq
    - proteomics
    - genomics
    - epigenomics
    - metabolomics
    - spatial omics
    - RNA-seq


  methods:
    - deep learning
    - graph neural network
    - VAE
    - Bayesian
    - Flow
    - Flow Matching
    - diffusion model
    - contrastive learning
    - generative model
    - transformer
    - causal inference
    - reinforcement learning
    - self-supervised learning
    - few-shot learning
    - meta-learning
    - transfer learning
    - federated learning
    - multi-task learning
    - ensemble learning
    - active learning
    - semi-supervised learning
    - unsupervised learning

  tasks:
    - cell type annotation
    - trajectory inference
    - batch correction
    - data integration
    - gene regulatory network
    - virtual cell

max_papers_per_day: 10
days_back: 2
